---
- name: set net.ipv4.ip_forward 1
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: set timezone to UTC
  timezone:
    name: UTC

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'

- name: Disable swap
  command: /sbin/swapoff -a
  changed_when: false
  ignore_errors: yes
  